[package]
name = "media_core_app"
version = "0.1.0"
edition = "2024"

[dependencies]
media_core = { git = "https://github.com/liren0907/rtsp_stream_extractor" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
